version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: sh /noice/init.sh
    volumes:
      - .:/noice
    ports:
      - "3000:3000"
    depends_on:
      - db
    working_dir: /noice
    stdin_open: true
    tty: true